# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Christos Despotakis
title: Senior Network System Administrator
email: christos@despotak.is
website: christos.despotak.is

# Social links
twitter_username: despotak
github_username:  despotak
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: despotak
# pinterest_username: jekyll
youtube_username: despotak
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Christos Despotakis is a freelancer video game designer, developer, and software engineer. He obtained his BCompSc from [University of Crete](https://www.uoc.gr), [Computer Science Department](https://www.csd.uoc.gr) and he has also studied Geology and Mathematics at the [Univercity of Athens](https://www.uoa.gr). He is awarded an undergraduate scholarship from [ICS-FORTH](https://www.ics.forth.gr/) for his Diploma work on Interactive Educative Game for the [Ambient Intelligence Lab (AmI)](http://www.ics.forth.gr/ami/index_main.php?l=e&amp;c=4).

  I am most skilled in: <mark>C/C++</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Role Playing games
   - Video Games
   - Cycling

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
