# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Christos Despotakis
title: Software Architect and Engineer
email: christos@despotak.is
website: christos.despotak.is

# Social links
# -- Work & Carreer --
github_username:  despotak
linkedin_username: despotak
# -- Social & Friends --
twitter_username: despotak
# facebook_username: jekyll
# googleplus_username: +jekyll
# dribbble_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
# pinterest_username: jekyll
reddit_username: despotak
# -- Video & Livestreaming --
youtube_username: despotak
twitch_username: cdr_archangel
mixer_username: cdr_archangel
# -- VoIP & Chat --

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Christos Despotakis is a freelancer video game designer, developer, and software engineer. He obtained his BCompSc from [University of Crete](https://www.uoc.gr), [Computer Science Department](https://www.csd.uoc.gr) and he has also studied Geology and Mathematics at the [Univercity of Athens](https://www.uoa.gr). He is awarded an undergraduate scholarship from [ICS-FORTH](https://www.ics.forth.gr/) for his Diploma work on Interactive Educative Game for the [Ambient Intelligence Lab (AmI)](http://www.ics.forth.gr/ami/index_main.php?l=e&amp;c=4).

  He is most skilled in: <mark>C/C++</mark> and <mark>Eating Pizza</mark>.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside his interests in software engineering some of his other interests and hobbies are:
   - Pen & Paper Role Playing Games
   - Video Games
   - Cycling

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
